# Generated by Django 6.0.3 on 2026-03-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarefasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tarefa', models.TextField(blank=True, null=True)),
                ('feito', models.BooleanField(default=False)),
                ('dia', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
